<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="Environment.props" />
  <Import Project="DoPrebuild.props" />
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>10.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SailingBagpipes</RootNamespace>
    <AssemblyName>SailingBagpipes</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Core" Version="5.4.19" />
    <PackageReference Include="JotunnLib" Version="2.*" />
  </ItemGroup>
</Project>
